# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loadTrie <- function(trieStr) {
    .Call(`_rflashtext_loadTrie`, trieStr)
}

buildTrie <- function(keys, values, id) {
    .Call(`_rflashtext_buildTrie`, keys, values, id)
}

addKeysWords <- function(ptr, keys, values, id) {
    .Call(`_rflashtext_addKeysWords`, ptr, keys, values, id)
}

dumpTrie <- function(ptr) {
    .Call(`_rflashtext_dumpTrie`, ptr)
}

containKeys <- function(ptr, keys, id) {
    .Call(`_rflashtext_containKeys`, ptr, keys, id)
}

getWords <- function(ptr, keys, id) {
    .Call(`_rflashtext_getWords`, ptr, keys, id)
}

findKeys <- function(ptr, sentences, word_chars, id, span_info) {
    .Call(`_rflashtext_findKeys`, ptr, sentences, word_chars, id, span_info)
}

replaceKeys <- function(ptr, sentences, word_chars, id) {
    .Call(`_rflashtext_replaceKeys`, ptr, sentences, word_chars, id)
}

